import { useEffect, useRef, useState } from 'react'
import toast, { Toaster } from 'react-hot-toast'
import { CalendarDays, MapPin, Users, LogIn, LogOut, Award, ClipboardCheck, Settings, Plus, CreditCard, Download, CheckCircle2, XCircle, Search, UserRound, FileText, ShieldCheck, BookOpen, ListChecks } from 'lucide-react'
import api from './api/client'
import { useAuth } from './context/AuthContext'
import InactivityTimeout from './components/InactivityTimeout'
import MfaModal from './components/MfaModal'
import MfaSetup from './components/MfaSetup'
import CertificateVerify from './pages/CertificateVerify'
import DocumentationView from './pages/DocumentationView'
import './App.css'

const pretty = v => String(v || '').replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase())
const date = v => v ? new Date(v).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'
const blankEvent = { title:'', description:'', category:'Technology', location:'', start_date:'', end_date:'', registration_deadline:'', fee:0, capacity:100, banner_color:'#4f46e5' }

export default function App() {
  const auth = useAuth()
  const [user,setUser]=useState(null),[events,setEvents]=useState([]),[page,setPage]=useState('browse'),[loading,setLoading]=useState(true),[authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState('login'),[form,setForm]=useState(blankEvent),[regs,setRegs]=useState([]),[certs,setCerts]=useState([]),[selected,setSelected]=useState(null),[attendance,setAttendance]=useState([]),[stats,setStats]=useState(null),[users,setUsers]=useState([]),[settings,setSettings]=useState({}),[notifications,setNotifications]=useState([])
  const initialLoadStarted=useRef(false)
  const fail=e=>toast.error(e.response?.data?.error||'Something went wrong. Please try again.')
  const loadEvents=async all=>setEvents((await api.get(all?'/symposiums/all':'/symposiums?upcoming=true')).data.symposiums)
  const refresh=async active=>{try{const u=active||user;await loadEvents(['admin','organizer','coordinator'].includes(u?.role));if(u){setNotifications((await api.get('/notifications')).data.notifications)}if(u?.role==='participant'){const[r,c]=await Promise.all([api.get('/registrations/my'),api.get('/certificates/my')]);setRegs(r.data.registrations);setCerts(c.data.certificates)}if(['admin','coordinator'].includes(u?.role))setStats((await api.get('/admin/stats')).data.stats);if(u?.role==='admin'){setUsers((await api.get('/admin/users?limit=100')).data.users);setSettings((await api.get('/admin/settings')).data.settings)}}catch(e){if(active||user)fail(e)}finally{setLoading(false)}}
  useEffect(()=>{if(initialLoadStarted.current)return;initialLoadStarted.current=true;(async()=>{try{const{data}=await api.get('/auth/me');setUser(data.user);await refresh(data.user)}catch{await loadEvents()}finally{setLoading(false)}})()},[])
  const login=async input=>{try{const response=await auth.login(input);if(response.mfaRequired)return;setUser(response.data.user);setAuthOpen(false);setPage('dashboard');await refresh(response.data.user);toast.success(`Welcome back, ${response.data.user.name}`)}catch(e){fail(e)}}
  const signup=async input=>{try{const{data}=await api.post('/auth/register',input);if(data.verification_token){const token=window.prompt('Local demo email verification token:',data.verification_token);if(token){await api.post('/auth/verify-email',{token});toast.success('Email verified. You can sign in.')}else toast.success('Account created. Verify your email before signing in.')}else toast.success('Account created. Check your email for a verification link.');setAuthMode('login')}catch(e){fail(e)}}
  const forgotPassword=async()=>{const email=window.prompt('Enter your account email:');if(!email)return;try{const{data}=await api.post('/auth/forgot-password',{email});if(data.reset_token){const token=window.prompt('Local demo password reset token:',data.reset_token);if(!token)return;const password=window.prompt('Enter a new password (8+ chars, uppercase, number, special character):');if(!password)return;await api.post('/auth/reset-password',{token,password});toast.success('Password reset. Please sign in.')}else toast.success(data.message)}catch(e){fail(e)}}
  const logout=async()=>{await auth.logout();setUser(null);setPage('browse');setRegs([]);setCerts([]);await loadEvents();toast.success('Signed out')}
  const register=async id=>{try{const{data}=await api.post('/registrations',{symposium_id:id});toast.success(data.payment_required?'Registration created. Complete payment in My registrations.':'Registration confirmed.');setPage('registrations');await refresh()}catch(e){fail(e)}}
  const pay=async id=>{try{await api.post(`/registrations/${id}/payment`,{method:'card'});toast.success('Demo payment successful.');await refresh()}catch(e){fail(e)}}
  const cancel=async id=>{if(!window.confirm('Cancel this registration?'))return;try{await api.post(`/registrations/${id}/cancel`);toast.success('Registration cancelled.');await refresh()}catch(e){fail(e)}}
  const create=async e=>{e.preventDefault();try{await api.post('/symposiums',{...form,fee:Number(form.fee),capacity:Number(form.capacity)});toast.success(user.role==='organizer'?'Submitted for approval.':'Symposium created.');setForm(blankEvent);await refresh()}catch(e){fail(e)}}
  const approve=async(id,action)=>{try{await api.post(`/symposiums/${id}/${action}`);toast.success(`Symposium ${action}d.`);await refresh()}catch(e){fail(e)}}
  const viewAttendance=async event=>{try{const{data}=await api.get(`/attendance/symposium/${event.id}`);setSelected(data.symposium);setAttendance(data.attendance);setPage('attendance')}catch(e){fail(e)}}
  const mark=async(id,present)=>{try{await api.post('/attendance/mark',{registration_id:id,present});setAttendance(x=>x.map(a=>a.registration_id===id?{...a,attendance_marked:present?1:0}:a));toast.success('Attendance updated.')}catch(e){fail(e)}}
  const generate=async()=>{try{const{data}=await api.post('/certificates/generate',{bulk_symposium_id:selected.id});toast.success(data.message);viewAttendance(selected)}catch(e){fail(e)}}
  const updateUser=async(id,body)=>{try{await api.put(`/admin/users/${id}`,body);toast.success('User updated.');refresh()}catch(e){fail(e)}}
  const markRead=async id=>{try{await api.post(`/notifications/${id}/read`);setNotifications(x=>x.map(n=>n.id===id?{...n,read_at:new Date().toISOString()}:n))}catch(e){fail(e)}}
  const checkin=async token=>{try{const{data}=await api.post('/attendance/check-in',{token,symposium_id:selected.id});toast.success(`Checked in ${data.participant_name}.`);if(selected)viewAttendance(selected)}catch(e){fail(e)}}
  const revokeCertificate=async uuid=>{const reason=window.prompt('Why are you revoking this certificate?');if(!reason)return;try{await api.post(`/certificates/${uuid}/revoke`,{reason});toast.success('Certificate revoked.');if(selected)viewAttendance(selected)}catch(e){fail(e)}}
  const exportReport=async id=>{try{const response=await api.get(`/admin/reports/attendance.csv?symposium_id=${id}`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=`symposium-${id}-attendance.csv`;a.click();URL.revokeObjectURL(url)}catch(e){fail(e)}}
  if(loading)return <div className="loading">Loading SymposiHub…</div>
  return <><Toaster position="top-right"/><InactivityTimeout/><header className="topbar"><button className="brand" onClick={()=>setPage('browse')}><span>SH</span><div>SymposiHub<small>Registration and certificates</small></div></button><nav><button onClick={()=>setPage('browse')}>Explore</button><button onClick={()=>setPage('verify')}>Verify</button><button onClick={()=>setPage('docs')}>Documentation</button>{user?<><button onClick={()=>setPage('dashboard')}>Dashboard</button><button onClick={()=>setPage('notifications')}>Notifications {notifications.filter(n=>!n.read_at).length>0&&`(${notifications.filter(n=>!n.read_at).length})`}</button><button className="profile" onClick={()=>setPage('account')}><UserRound size={17}/>{user.name}<Badge value={user.role}/></button><button className="btn btn-ghost btn-sm" onClick={logout}><LogOut size={15}/> Sign out</button></>:<button className="btn btn-primary" onClick={()=>{setAuthMode('login');setAuthOpen(true)}}><LogIn size={16}/> Sign in</button>}</nav></header>
  {page==='browse'&&<Browse events={events} user={user} register={register} signIn={()=>setAuthOpen(true)}/>} {page==='verify'&&<CertificateVerify/>} {page==='docs'&&<DocumentationView/>} {page==='notifications'&&user&&<Notifications items={notifications} markRead={markRead}/>} {page==='dashboard'&&user&&<Dashboard {...{user,stats,events,regs,certs,setPage}}/>} {page==='registrations'&&<Registrations regs={regs} {...{pay,cancel}}/>} {page==='certificates'&&<Certificates certs={certs}/>} {page==='manage'&&user?.role!=='participant'&&<Manage {...{events,user,form,setForm,create,approve,viewAttendance,exportReport}}/>} {page==='attendance'&&selected&&<Attendance event={selected} {...{attendance,mark,generate,checkin,revokeCertificate}}/>} {page==='admin'&&user?.role==='admin'&&<Admin {...{users,settings,setSettings,updateUser}}/>} {page==='account'&&user&&<Account user={user}/>} {authOpen&&<Auth mode={authMode} {...{setAuthMode,login,signup,forgotPassword}} close={()=>setAuthOpen(false)}/>} {auth.mfaChallenge&&<MfaModal close={()=>setAuthOpen(false)} onSuccess={()=>{setUser(auth.user);setPage('dashboard')}}/>}</>
}
function Browse({events,user,register,signIn}){const[q,setQ]=useState('');const list=events.filter(e=>`${e.title} ${e.location} ${e.category}`.toLowerCase().includes(q.toLowerCase()));return <main><section className="hero"><div><p className="eyebrow">Academic events made simple</p><h1>One place to register, attend, and receive certificates.</h1><p>Discover upcoming symposiums and manage your complete event journey online.</p><a className="btn btn-primary btn-lg" href="#events">Browse symposiums</a></div><div className="hero-panel"><CalendarDays size={32}/><strong>{events.length} upcoming symposiums</strong><span>Registration, payment, attendance, and verified certificates in one secure system.</span></div></section><section id="events" className="section"><div className="section-head"><div><p className="eyebrow">Discover</p><h2>Upcoming symposiums</h2></div><label className="search"><Search size={18}/><input placeholder="Search by title, topic, or location" value={q} onChange={e=>setQ(e.target.value)}/></label></div><div className="event-grid">{list.map(e=><EventCard key={e.id} event={e} action={user?.role==='participant'?()=>register(e.id):user?null:signIn} label={user?.role==='participant'?'Register now':'Sign in to register'}/>)}</div>{!list.length&&<Empty text="No upcoming symposiums match your search."/>}</section></main>}
function EventCard({event,action,label}){return <article className="event-card"><div className="event-color" style={{background:event.banner_color}}><span>{event.category||'Symposium'}</span><strong>{date(event.start_date)}</strong></div><div className="event-body"><h3>{event.title}</h3><p className="clamp">{event.description||'Join an engaging academic symposium.'}</p><p><MapPin size={16}/>{event.location}</p><p><Users size={16}/>{event.registered_count} / {event.capacity} registered</p><div className="event-bottom"><strong>{Number(event.fee)===0?'Free':`₹${event.fee}`}</strong>{action&&<button className="btn btn-primary btn-sm" onClick={action}>{label}</button>}</div></div></article>}
function Dashboard({user,stats,events,regs,certs,setPage}){const cards=user.role==='participant'?[['My registrations',regs.length,'registrations',CalendarDays],['Certificates',certs.length,'certificates',Award],['Attendance confirmed',regs.filter(x=>x.attendance_marked).length,'registrations',CheckCircle2]]:[['Symposiums',user.role==='organizer'?events.length:stats?.total_symposiums||0,'manage',CalendarDays],['Registrations',stats?.total_registrations||'—','manage',Users],['Certificates',stats?.total_certificates||'—','manage',Award]];return <main className="app-main"><PageTitle title={`Welcome, ${user.name.split(' ')[0]}`} subtitle={`Signed in as ${pretty(user.role)}`}/><div className="stat-grid">{cards.map(([label,value,to,Icon])=><button className="stat-card card" key={label} onClick={()=>setPage(to)}><Icon/><strong>{value}</strong><span>{label}</span></button>)}</div><section className="card action-panel"><div><h2>{user.role==='participant'?'Ready for your next symposium?':'Manage your events'}</h2><p>{user.role==='participant'?'Browse approved symposiums, check registration status, and download earned certificates.':'Create events, monitor registrations, verify attendance, and issue certificates.'}</p></div><button className="btn btn-primary" onClick={()=>setPage(user.role==='participant'?'browse':'manage')}>{user.role==='participant'?'Explore events':'Open management'}</button></section>{user.role==='admin'&&<button className="btn btn-ghost" onClick={()=>setPage('admin')}><Settings size={16}/> System administration</button>}</main>}
function Registrations({regs,pay,cancel}){return <main className="app-main"><PageTitle title="My registrations" subtitle="Track your symposium and payment status. Demo payments do not charge real money."/>{regs.length?<div className="list">{regs.map(r=><article className="record card" key={r.id}><div><h3>{r.symposium_title}</h3><p><CalendarDays size={15}/>{date(r.start_date)} · <MapPin size={15}/>{r.location}</p></div><div className="record-status"><Badge value={r.status}/><Badge value={r.payment_status}/></div><div className="row-actions">{r.checkin_token&&<img width="80" height="80" alt="Your event check-in QR code" title="Show this QR code at the event" src={`/api/attendance/qr/${r.id}`} />}{r.payment_status==='pending'&&<button className="btn btn-primary btn-sm" onClick={()=>pay(r.id)}><CreditCard size={15}/> Pay ₹{r.fee}</button>}{['registered','pending_payment','confirmed'].includes(r.status)&&<button className="btn btn-ghost btn-sm" onClick={()=>cancel(r.id)}>Cancel</button>}</div></article>)}</div>:<Empty text="You have not registered for any symposiums yet."/>}</main>}

function Notifications({items,markRead}){return <main className="app-main"><PageTitle title="Notifications" subtitle="Registration and payment updates for your account."/>{items.length?<div className="list">{items.map(n=><article className="record card" key={n.id}><div><h3>{n.title}</h3><p>{n.message}</p><small>{date(n.created_at)}</small></div>{!n.read_at&&<button className="btn btn-ghost btn-sm" onClick={()=>markRead(n.id)}>Mark read</button>}</article>)}</div>:<Empty text="No notifications yet."/>}</main>}
function Certificates({certs}){return <main className="app-main"><PageTitle title="My certificates" subtitle="Download your issued and verifiable participation certificates."/>{certs.length?<div className="event-grid">{certs.map(c=><article className="certificate card" key={c.cert_uuid}><Award size={34}/><p className="eyebrow">Certificate of participation</p><h3>{c.symposium_title}</h3><p>Issued {date(c.issue_date)}</p><code>{c.cert_uuid}</code><a className="btn btn-primary" href={`/api/certificates/${c.cert_uuid}/download`}><Download size={16}/> Download PDF</a></article>)}</div>:<Empty text="Certificates appear here after the organizer marks your attendance and issues them."/>}</main>}
function Manage({events,user,form,setForm,create,approve,viewAttendance,exportReport}){const set=e=>setForm({...form,[e.target.name]:e.target.value});return <main className="app-main"><PageTitle title="Symposium management" subtitle="Create events and manage the registration lifecycle."/><div className="manage-grid"><form className="card event-form" onSubmit={create}><h2><Plus size={19}/> Create symposium</h2><input className="form-input" required name="title" placeholder="Symposium title" value={form.title} onChange={set}/><textarea className="form-input" name="description" placeholder="Short description" value={form.description} onChange={set}/><div className="form-row"><input className="form-input" name="category" placeholder="Category" value={form.category} onChange={set}/><input className="form-input" required name="location" placeholder="Location" value={form.location} onChange={set}/></div><div className="form-row"><label>Start<input className="form-input" required type="date" name="start_date" value={form.start_date} onChange={set}/></label><label>End<input className="form-input" required type="date" name="end_date" value={form.end_date} onChange={set}/></label></div><label>Registration deadline<input className="form-input" required type="date" name="registration_deadline" value={form.registration_deadline} onChange={set}/></label><div className="form-row"><label>Fee ₹<input className="form-input" type="number" min="0" name="fee" value={form.fee} onChange={set}/></label><label>Capacity<input className="form-input" type="number" min="1" name="capacity" value={form.capacity} onChange={set}/></label></div><button className="btn btn-primary">Create symposium</button></form><section className="card manage-list"><h2>Your accessible symposiums</h2>{events.map(e=><div className="manage-item" key={e.id}><div><h3>{e.title}</h3><p>{date(e.start_date)} · {e.registered_count}/{e.capacity} registrations</p><Badge value={e.status}/></div><div className="row-actions">{['admin','coordinator'].includes(user.role)&&e.status==='pending_approval'&&<><button className="btn btn-success btn-sm" onClick={()=>approve(e.id,'approve')}>Approve</button><button className="btn btn-danger btn-sm" onClick={()=>approve(e.id,'reject')}>Reject</button></>}{user.role!=='coordinator'&&<><button className="btn btn-ghost btn-sm" onClick={()=>viewAttendance(e)}><ClipboardCheck size={15}/> Attendance</button><button className="btn btn-ghost btn-sm" onClick={()=>exportReport(e.id)}>Export CSV</button></>}</div></div>)}</section></div></main>}
function Attendance({event,attendance,mark,generate,checkin,revokeCertificate}){const[token,setToken]=useState('');const submit=e=>{e.preventDefault();checkin(token);setToken('')};return <main className="app-main"><PageTitle title={`Attendance for ${event.title}`} subtitle="Scan a participant's check-in QR code with a scanner, or enter its code below."/><form className="card event-form" onSubmit={submit}><label>QR check-in code<input className="form-input" autoFocus value={token} onChange={e=>setToken(e.target.value)} placeholder="Scan QR code here" required/></label><button className="btn btn-primary">Check in participant</button></form><div className="card table-container"><table><thead><tr><th>Participant</th><th>Email</th><th>Payment</th><th>Attendance</th><th>Certificate</th></tr></thead><tbody>{attendance.map(a=><tr key={a.registration_id}><td>{a.participant_name}</td><td>{a.participant_email}</td><td><Badge value={a.payment_status}/></td><td><button className={`attendance-btn ${a.attendance_marked?'present':''}`} onClick={()=>mark(a.registration_id,!a.attendance_marked)}>{a.attendance_marked?<><CheckCircle2 size={16}/> Present</>:<><XCircle size={16}/> Absent</>}</button></td><td>{a.cert_uuid?<><Badge value={a.certificate_revoked_at?'Revoked':'Issued'}/>{!a.certificate_revoked_at&&<button className="btn btn-ghost btn-sm" onClick={()=>revokeCertificate(a.cert_uuid)}>Revoke</button>}</>:'—'}</td></tr>)}</tbody></table></div><button className="btn btn-primary" onClick={generate}><Award size={16}/> Generate certificates for all present participants</button></main>}
function Admin({users,settings,setSettings,updateUser}){const set=e=>setSettings({...settings,[e.target.name]:e.target.value});const save=async e=>{e.preventDefault();try{await api.put('/admin/settings',settings);toast.success('Settings saved.')}catch(x){toast.error(x.response?.data?.error||'Could not save settings.')}};return <main className="app-main"><PageTitle title="System administration" subtitle="Manage user access and system configuration."/><div className="manage-grid"><section className="card admin-users"><h2>Users</h2>{users.map(u=><div className="user-row" key={u.id}><div><strong>{u.name}</strong><small>{u.email}</small></div><select className="form-input" value={u.role} onChange={e=>updateUser(u.id,{role:e.target.value})}><option>participant</option><option>organizer</option><option>coordinator</option><option>admin</option></select><button className={`btn btn-sm ${u.is_active?'btn-ghost':'btn-success'}`} onClick={()=>updateUser(u.id,{is_active:!u.is_active})}>{u.is_active?'Disable':'Enable'}</button></div>)}</section><form className="card event-form" onSubmit={save}><h2><Settings size={19}/> Settings</h2><label>Site name<input className="form-input" name="site_name" value={settings.site_name||''} onChange={set}/></label><label>Contact email<input className="form-input" name="contact_email" value={settings.contact_email||''} onChange={set}/></label><label>Session timeout minutes<input className="form-input" type="number" name="session_timeout_minutes" value={settings.session_timeout_minutes||''} onChange={set}/></label><label>Self registration<select className="form-input" name="allow_self_registration" value={settings.allow_self_registration||''} onChange={set}><option value="true">Allowed</option><option value="false">Disabled</option></select></label><button className="btn btn-primary">Save settings</button></form></div></main>}
function Account({user}){return <main className="app-main"><PageTitle title="Account" subtitle="Your active access profile."/><section className="card account"><UserRound size={40}/><h2>{user.name}</h2><p>{user.email}</p><Badge value={user.role}/><p>{user.mfa_enabled?'Multi-factor authentication is enabled.':'Multi-factor authentication is not enabled.'}</p></section></main>}
function Auth({mode,setAuthMode,close,login,signup,forgotPassword}){const[input,setInput]=useState({name:'',email:'',password:''});const submit=e=>{e.preventDefault();mode==='login'?login(input):signup(input)};return <div className="modal-overlay"><form className="modal auth" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">SymposiHub</p><h2>{mode==='login'?'Welcome back':'Create an account'}</h2><p>{mode==='login'?'Sign in to manage your symposium journey.':'New accounts are created as participant accounts.'}</p>{mode==='register'&&<input className="form-input" required placeholder="Full name" value={input.name} onChange={e=>setInput({...input,name:e.target.value})}/>}<input className="form-input" required type="email" placeholder="Email address" value={input.email} onChange={e=>setInput({...input,email:e.target.value})}/><input className="form-input" required type="password" placeholder="Password" value={input.password} onChange={e=>setInput({...input,password:e.target.value})}/>{mode==='register'&&<small>Password: 8+ characters with uppercase, number, and special character.</small>}<button className="btn btn-primary">{mode==='login'?'Sign in':'Create account'}</button>{mode==='login'&&<button type="button" className="link-btn" onClick={forgotPassword}>Forgot password?</button>}<button type="button" className="link-btn" onClick={()=>setAuthMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Register':'Already registered? Sign in'}</button>{mode==='login'&&<small className="demo">Demo: student@symposium.edu / Student@123</small>}</form></div>}
function Badge({value}){return <span className={`badge status-${String(value).toLowerCase().replaceAll(' ','_')}`}>{pretty(value)}</span>}function PageTitle({title,subtitle}){return <header className="page-heading"><p className="eyebrow">SymposiHub</p><h1>{title}</h1><p>{subtitle}</p></header>}function Empty({text}){return <div className="empty-state"><FileText size={38}/><p>{text}</p></div>}
